TARGET_VELOCITY: 2
VELOCITY_RESOLUTION: 0.1
YAWRATE_RESOLUTION: 0.1
PREDICT_TIME: 5
TO_GOAL_COST_GAIN: 0.9
SPEED_COST_GAIN: 0.2
OBSTACLE_COST_GAIN: 0.2
ANGLE_RESOLUTION: 0.0087
MAX_DIST: 10.0
GOAL_THRESHOLD: 1
TURN_DIRECTION_THRESHOLD: 0.2
